In [ ]:
# Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import _pickle as cPickle
import os


# Directories
data_dir = '../data'
scp_instances_dir = os.path.join(data_dir, 'scp_instances')

scp_instances_list =[i for i in os.listdir(scp_instances_dir) if not i.startswith('.')]

print("Number of instances in folder: {}".format(len(scp_instances_list)))

In [ ]:
# Read the instances, we have to read them with old-school Python to decode the different dimensions of each line

# Create a list of all the instances
all_scp_instances = list()
for idx, filename in enumerate(scp_instances_list):
    instance = open(os.path.join(scp_instances_dir, filename))
    # print("Current filename: {}".format(filename))

    # We create a list to append the diferent lines
    lines = list()

    for i, line in enumerate(instance):
        # print(i, len(line))
        lines.append(line.split(" "))

    instance.close()
    

    # print("This file has a total of {} lines.".format(len(lines)))
    
    
    # We reuse the variable into a dict to save several attributes
    instance = dict()
    
    
    # Clean the strings that resulted from the file reading
    for i, line in enumerate(lines):
        line.remove('\n')
        line.remove('')

    
    # Indices list for the costs and the subsets of variable size
    indices_of_costs = list()
    
    # Check the lines that contain only one element (the cost?)
    for i, line in enumerate(lines):
        if len(line) == 1:
            indices_of_costs.append(i)
    
    # Append the argument of the last line
    indices_of_costs.append(len(lines)-1)
    
    
    # Create the instance
    # 1st Index is the Coordinates (?)
    instance['coordinates'] = np.array(lines[0], dtype=int)
    
    # 2nd Index is the Map (?)
    # We have to get all the elements of the map (?) first
    kind_of_map = list()
    for i in range(1, indices_of_costs[0]):
        for j in lines[i]:
            kind_of_map.append(j)
            
    instance['map'] = np.array(kind_of_map, dtype=int)
    
    # 3rd Index is a dict with the costs and the subsets of variable size
    # instance['costs_subsets'] = dict()
    cost_subsets = list()
    # We use the indices_of_costs to get this places and we know that until the next one we are facing subsets!
    for i, idx in enumerate(indices_of_costs):
        # We get the cost (it is indexed at position 0)
        cost = int(lines[idx][0])
        # print(cost)
        
        # Now we get the subset
        subset = list()
        if idx < indices_of_costs[-1]:
        # if idx < indices_of_costs[i+1] and indices_of_costs[i+1] < indices_of_costs[-1]:
            for s in range(idx+1, indices_of_costs[i+1]):
                # print(s, lines[s])
                for j in lines[s]:
                    subset.append(j)
                    
        
        subset = np.array(subset, dtype=int)
        # print(cost, subset)
        
        cost_subsets.append([cost, subset])
        # print(cost_subsets)
    
    instance['costs_subsets'] = cost_subsets
        
    # Append the instance to our list
    all_scp_instances.append(instance)

# Print the np.shape of all instances array
print("We currently have {} instances.".format(np.shape(all_scp_instances)))

In [ ]:
# Save file for further use
with open(os.path.join(data_dir, 'scp_intances_initial.pickle'), 'wb') as f:
    cPickle.dump(all_scp_instances, f, -1)

In [ ]:
# Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import _pickle as cPickle
import os


# Directories
data_dir = '../data'
scp_instances_dir = os.path.join(data_dir, 'scp_instances')

with open(os.path.join(data_dir, 'scp_intances_initial.pickle'), 'rb') as f:
    scp_instances = cPickle.load(f)

# scp_instances

In [ ]:
scp_instances[0]['coordinates'], len(scp_instances[0]['map']), len(scp_instances[0]['costs_subsets'])

In [1]:
# Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import _pickle as cPickle
import os
from utilities import SCPInstance


# Directories
data_dir = '../data'
scp_instances_dir = os.path.join(data_dir, 'scp_instances')

scp_instances_list =[i for i in os.listdir(scp_instances_dir) if not i.startswith('.')]

print("Number of instances in folder: {}".format(len(scp_instances_list)))

test = SCPInstance(os.path.join(scp_instances_dir, scp_instances_list[0]))

Number of instances in folder: 42
21
16
16
17
18
22
31
16
22
15
26
22
15
22
19
18
25
22
24
22
13
19
24
12
19
19
17
14
17
18
20
17
20
28
16
18
17
26
20
20
17
21
22
22
24
23
20
16
24
24
20
23
20
26
27
27
19
20
28
14
23
11
21
19
22
19
26
20
21
25
21
26
20
20
19
21
29
18
20
18
19
27
19
15
14
25
23
9
22
20
25
23
22
25
19
25
19
20
27
10
18
18
20
18
21
22
24
18
25
18
13
21
20
17
25
24
19
21
18
12
21
19
19
17
12
22
15
15
22
17
21
16
18
23
15
18
22
19
20
14
22
20
17
15
22
27
22
16
21
23
19
22
20
21
20
18
23
14
11
14
23
17
19
23
23
16
24
17
25
20
17
17
13
20
23
10
23
16
22
24
27
21
24
17
11
29
24
18
18
18
19
16
16
22
23
22
20
14
22


In [2]:
test.scp_instance_filename

'../data/scp_instances/scp42.txt'

In [4]:
test.scp_number_of_attributes, test.scp_instance_attribute_map.shape, test.scp_number_of_attributes == test.scp_instance_attribute_map.shape[0]

(1000, (1000,), True)

In [6]:
test.scp_instance_attribute_map, np.unique(test.scp_instance_attribute_map)# test.scp_instance_attribute_map

(array([  1,   1,   1,   1,   1,   1,   1,   1,   1,   2,   2,   2,   2,
          2,   2,   2,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,
          3,   3,   4,   4,   4,   4,   4,   4,   4,   4,   4,   4,   4,
          4,   4,   4,   5,   5,   5,   5,   5,   5,   5,   5,   5,   5,
          5,   5,   5,   5,   5,   6,   6,   6,   6,   6,   6,   6,   6,
          6,   6,   7,   7,   7,   7,   7,   7,   7,   7,   8,   8,   8,
          8,   8,   8,   9,   9,   9,   9,   9,   9,   9,   9,   9,  10,
         10,  10,  10,  10,  10,  10,  10,  10,  10,  11,  11,  11,  11,
         11,  11,  11,  11,  11,  11,  11,  12,  12,  12,  12,  12,  12,
         12,  12,  12,  12,  13,  13,  13,  13,  13,  13,  13,  13,  13,
         13,  13,  13,  13,  13,  14,  14,  14,  14,  14,  14,  14,  14,
         15,  15,  15,  15,  15,  15,  15,  15,  15,  16,  16,  16,  16,
         16,  16,  16,  16,  16,  16,  17,  17,  17,  17,  17,  17,  17,
         17,  17,  18,  18,  18,  18,  18,  18,  18

In [7]:
test.scp_number_of_subsets

200

In [8]:
np.shape(test.scp_instance_all_subsets), test.scp_instance_all_subsets, len(test.scp_instance_all_subsets) == test.scp_number_of_subsets

((200,),
 [array([ 18, 113, 164, 270, 309, 320, 381, 404, 410, 433, 452, 491, 587,
         639, 844, 855, 935, 970]),
  array([ 10,  17,  59, 184, 238, 254, 355, 419, 423, 444, 448, 612, 625,
         677, 685, 688, 707, 757, 844, 948, 951]),
  array([220, 273, 284, 294, 346, 434, 446, 511, 587, 719, 746, 753, 788,
         923, 957, 975]),
  array([ 17,  28, 165, 218, 317, 340, 405, 407, 447, 463, 542, 662, 748,
         920, 966, 987]),
  array([ 17,  70, 104, 124, 163, 203, 289, 363, 381, 603, 634, 657, 801,
         862, 886, 950, 993]),
  array([177, 178, 206, 210, 234, 254, 340, 344, 370, 380, 406, 412, 702,
         704, 745, 767, 910, 914]),
  array([ 18,  22, 146, 220, 223, 238, 239, 309, 429, 477, 535, 557, 581,
         643, 682, 796, 799, 801, 866, 880, 908, 982]),
  array([ 29,  33,  68, 112, 187, 245, 285, 343, 367, 391, 408, 418, 444,
         535, 569, 575, 631, 632, 662, 705, 747, 770, 773, 775, 803, 856,
         864, 910, 951, 976, 997]),
  array([ 21, 127, 185, 294